name: part3 build and publish container
on:
  push:
    paths:
      - "**"
jobs:
  build-and-publish-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to the registry
        uses: azure/docker-login@v1
        with:
          login-server: idi2020.azurecr.io
          username: ${{ secrets.IDI2020_REGISTRY_USERNAME }}
          password: ${{ secrets.IDI2020_REGISTRY_PASSWORD }}
      - name: Build and publish container
<<<<<<< HEAD
        working-directory: ./
=======
        working-directory: ./swpq/part3/container-publish/containerbuild
>>>>>>> 8ca10f275f5beb161abdf94d5a153f61533a038e
        run: ./stateexample build-$GITHUB_RUN_NUMBER idi2020.azurecr.io
